version: "3.8"
name: permissions-localtest

services:
  db:
    container_name: db
    image: postgres:17
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  permissions:
    build: ..
    container_name: permissions
    restart: always
    environment:
      GRPC_PORT: 9090
      DB_USER: myuser
      DB_PASSWORD: mypassword
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: mydatabase
    ports:
      - "9090:9090"
    depends_on:
      - db

volumes:
  pgdata:
